spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        db-sm:
            driverClassName: "org.h2.Driver"
            url: jdbc:h2:mem:sco
            name: dev-integration-test
            username: sa
            password: sa
            hikari:
                   data-source-properties:
                        cachePrepStmts: true
                        prepStmtCacheSize: 250
                        prepStmtCacheSqlLimit: 2048
                        useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        properties:
            hibernate.generate_statistics: "true"
            hibernate.use_sql_comments: "true"
            hibernate.format_sql: "true"
            hibernate.show_sql: "true"