spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
            driver-class-name: "org.postgresql.Driver"
            url: jdbc:postgresql://localhost:5432/postgres?searchpath=films
            name: dev-integration-test
            username: postgres
            password: postgres
            hikari:
                   data-source-properties:
                        cachePrepStmts: true
                        prepStmtCacheSize: 250
                        prepStmtCacheSqlLimit: 2048
                        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: PostgreSQL
        properties:
            hibernate.generate_statistics: "false"
            hibernate.use_sql_comments: "true"
            hibernate.format_sql: "true"
            hibernate.show_sql: "true"
            hibernate.hbm2ddl.auto: "none"