spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
            driver-class-name: "org.postgresql.Driver"
            url: jdbc:postgresql://localhost:5432/postgres?searchpath=films
            name: dev-integration-test
            username: postgres
            password: postgres
            hikari:
                   data-source-properties:
                        cachePrepStmts: true
                        prepStmtCacheSize: 250
                        prepStmtCacheSqlLimit: 2048
                        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        database: PostgreSQL
        properties:
            hibernate.generate_statistics: "true"
            hibernate.use_sql_comments: "true"
            hibernate.format_sql: "true"
            hibernate.show_sql: "true"
            hibernate.hbm2ddl.auto: "none"
            hibernate.jdbc.batch_size: "1000"
            hibernate.order_inserts: "true"
            hibernate.order_updates: "true"
            hibernate.jdbc.batch_versioned_data: "true"

server:
  port: 8087

